<<<<<<< HEAD
scan_filter_chain:
=======
scan_to_scan_filter_chain:
>>>>>>> ros2
  ros__parameters:
    filter1:
      name: mask
      type: laser_filters/LaserScanMaskFilter
      params:
        masks:
          laser:
<<<<<<< HEAD
          - 100
          - 101
          - 102
          - 103
          - 104
          - 1000
          - 1001
          - 1002
=======
          - 100.
          - 101.
          - 102.
          - 103.
          - 104.
          - 1000.
          - 1001.
          - 1002.
>>>>>>> ros2
