scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: polygon_filter
      type: laser_filters/LaserScanPolygonFilter
      params:
        polygon_frame: base_link
        polygon: '[[0.0, 0.0], [0.1, 0.1], [0.1, 0.0], [0.0, -0.1]]'
        invert: false
        footprint_topic: base_footprint_exclude
